
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sql-password
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: "b40fe419-8e15-40e2-a309-2be0cb2a4f6f"   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: akskvteam11        # Set to the name of your key vault
    objects:  |
      array:
        - |
          objectName: SQL-PASSWORD
          objectAlias: SQL_PASSWORD
          objectType: secret
    tenantId: 5528dda0-af2c-42e1-8c4e-9ffc49bf3c56             # The tenant ID of the key vault

