apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
  labels:
    app: userprofile
    purpose: openhack-containers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
        - name: userprofile
          image: registryckv0271.azurecr.io/userprofile:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: SQL_USER
              value: "sqladmincKv0271"
            - name: SQL_PASSWORD
              value: "ChangeMe12345@@"
            - name: SQL_SERVER
              value: "sqlserverckv0271.database.windows.net"
            - name: SQL_DBNAME
              value: "mydrivingDB"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
          resources:
            requests:
              memory: 64Mi
              cpu: 200m
            limits:
              memory: 128Mi
              cpu: 400m
          volumeMounts:
            - name: secrets-store01-inline
              mountPath: "/secrets"
              readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "sql-password"
---

apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
  namespace: api
spec:
  selector:
    app: userprofile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
